---
- name: 既存のLaunchAgentを登録解除
  ansible.builtin.command: "launchctl bootout gui/{{ ansible_user_uid }}/{{ launchd_upgrade_label }}"
  changed_when: true
  failed_when: false
  listen: LaunchAgentを再読み込み

- name: LaunchAgentを登録
  ansible.builtin.command: "launchctl bootstrap gui/{{ ansible_user_uid }} {{ launchd_upgrade_plist }}"
  changed_when: true
  listen: LaunchAgentを再読み込み
