---
########################################################
# メインプレイブック
########################################################
- name: メインプレイブック
  hosts: localhost
  gather_facts: true
  become: false

  ########################################################
  # 各ロールの実行
  ########################################################
  roles:
    ########################################################
    # macOS専用role
    ########################################################
    - role: homebrew
      when: ansible_os_family == 'Darwin'
    - role: mas
      when: ansible_os_family == 'Darwin'
    - role: mac-setting
      when: ansible_os_family == 'Darwin'

    ########################################################
    # OS共通role
    ########################################################
    - role: asdf

    ########################################################
    # dotfiles管理（1Password認証が必要）
    ########################################################
    - role: chezmoi
