---
- name: 指定バージョンをインストール
  ansible.builtin.shell: "{{ mise_bin }} use --global {{ item.name }}@{{ item.version }}"
  loop: "{{ mise_tools_versions | default([]) }}"
  loop_control:
    label: "{{ item.name }}@{{ item.version }}"
  register: mise_install_result
  changed_when: "'Installing' in mise_install_result.stderr or 'installed' in mise_install_result.stderr"
  failed_when: false

- name: mise shimsを更新
  ansible.builtin.shell: "{{ mise_bin }} reshim"
  changed_when: false
