---
- name: Homebrewセットアップ
  tags:
    - install
    - upgrade
    - homebrew
  block:
    - name: Homebrewがインストールされているか確認
      ansible.builtin.stat:
        path: "{{ brew_bin }}"
      register: brew_stat

    - name: Homebrewが見つからない場合は処理を中断
      ansible.builtin.fail:
        msg: "Homebrewがインストールされていません。`make mac-bootstrap` を実行してください。"
      when: not brew_stat.stat.exists

    - name: Homebrew管理対象リストを集約
      ansible.builtin.set_fact:
        brew_formula_all: "{{ ((brew_formula | default([], true)) + (brew_formula_extra | default([], true))) | unique }}"
        brew_casks_normal_all: "{{ ((brew_casks_normal | default([], true)) + (brew_casks_normal_extra | default([], true))) | unique }}"
        brew_casks_sudo_required_all: "{{ ((brew_casks_sudo_required | default([], true)) + (brew_casks_sudo_required_extra | default([], true))) | unique }}"

    - name: Homebrewを最新版に更新
      community.general.homebrew:
        update_homebrew: true

- name: Homebrewパッケージインストール処理
  ansible.builtin.import_tasks: install.yml
  tags:
    - install
    - homebrew

- name: Homebrewパッケージアップグレード処理
  ansible.builtin.import_tasks: upgrade.yml
  tags:
    - upgrade
