---
- name: Homebrewセットアップ
  tags:
    - install
    - upgrade
    - homebrew
  block:
    - name: Homebrewがインストールされているか確認
      ansible.builtin.stat:
        path: "{{ homebrew_prefix }}/bin/brew"
      register: brew_stat

    - name: Homebrewが見つからない場合は処理を中断
      ansible.builtin.fail:
        msg: "Homebrewがインストールされていません。`make mac-bootstrap` を実行してください。"
      when: not brew_stat.stat.exists

    - name: Homebrewを最新版に更新
      community.general.homebrew:
        update_homebrew: true

- name: Homebrewパッケージインストール処理
  ansible.builtin.import_tasks: install.yml
  tags:
    - install
    - homebrew

- name: Homebrewパッケージアップグレード処理
  ansible.builtin.import_tasks: upgrade.yml
  tags:
    - upgrade
    - homebrew
