---
# マシン固有の設定テンプレート
# このファイルは mac-bootstrap.sh 実行時に {ホスト名}.yml としてコピーされます。
# group_vars/all.yml の共通設定に追加・上書きする内容を記述してください。

# Mac App Store アプリのインストール（true: 有効 / false: 無効）
enable_mas: true

# このマシンにだけ追加するFormulaパッケージ
brew_formula_extra:

# このマシンにだけ追加するCaskアプリ
brew_casks_normal_extra:
  - readdle-spark

# このマシンにだけ追加するCaskアプリ（sudo必要）
brew_casks_sudo_required_extra:
  - nordvpn