---
# Rays-MPPM5 マシン固有の設定
# group_vars/all.yml の共通設定に追加・上書きする内容を記述してください。

# このマシンにだけ追加するFormulaパッケージ
brew_formula_extra: []

# このマシンにだけ追加するCaskアプリ
brew_casks_normal_extra:
  - slack

# このマシンにだけ追加するCaskアプリ（sudo必要）
brew_casks_sudo_required_extra:
  - nordvpn

